### PR TITLE
Feature/gh coverage

### PR DESCRIPTION
**Pull request by jas88**
- Resume running RDMP UI tests (seem to run fine on Github)
- Generate Coveralls coverage data from Github not Appveyor
- Replace Appveyor with dummy code for now until Appveyor deleted

### CODE REVIEW

**Review by tznind — APPROVED** [review]

**Comment by tznind** [comment]
Have approved, theres a lot of failing checks and theres three seperate coverage percentages showing (26, 15 and 21).  Will these checks constantly fail? is there a way to get an average/accurate coverage metric? The value seems low.

**Comment by jas88** [comment]
Just two failing checks, one of which is Snyk which is just broken - there's an outstanding bug in the Coveralls dev backlog to fix the way their current code reports coverage multiple times to Github, once for each part of the run plus again for the overall figure, instead of just reporting the overall coverage when finished. 3 separate runs is fine (apart from that UI glitch with Github), Coveralls does combine the 3 into a single overall figure and report that as well - it's 57% now, and excluding a few things ("*.Designer.cs" maybe, "Annotations"?) would boost that further. Plus somehow it's picking up a netcoreapp2.2 shim in nuget.packages that we aren't testing - I'll see about excluding that soon too.

Before we merge there are two tests genuinely failing now (both from the UI Tests set, so haven't been run in CI for a while now): I had to disable ConvertNonPrimaryKeyColumn in ANOMigrationTests.cs since it doesn't pass even when run alone, and I can't see how to fix it either; also, I had to add "ExecuteAggregateGraph", "ExtractMetadata", "DateRange",  "AlterTableMakeDistinct" to the documentation whitelist for now.

**Comment by tznind** [comment]
That's great work thanks.

I'll look into `ANOMigrationTests` but they work regardless of order of execution when I run locally.  You can see this if you have visual studio installed and change the TestDatabases.txt to (you have to have also created the platform databases though):

```
ServerName:	(localdb)\MSSQLLocalDB
Prefix:	TEST_
```

image

**Comment by tznind** [comment]
I've created a new ticket for the ANO tests https://github.com/HicServices/RDMP/issues/391

**Pull request merged**
