### PR TITLE
Batching

### LINKED ISSUE #683: Buffer long data extractions to allow restarting at faliure point [Magalie]
It occurs very frequently that an extraction fails after many hours running due to various reasons which could be solved on the go and allow the extraction to finalise correctly. Most of the time  the reason is due to timeout / space disk / metadata error / wrong pipeline configuration and nothing can prevent this until an extract reach the point of failure after hours running.
The only options remaining ane then 
- run manually in SQL (but lose metadata which can't be generated separately or before the data extraction)
- Try again in RDMP and hope for the best. 

We face more and more big data extractions - and this is not sustainable as RDMP failures during extraction, delay a lot of projects releases. It can take a week just to extract all data for one single project.

If RDMP could memorise the latest point of execution are "pause" it until manual intervention resolve the issue - it would definitely help us and reduce significant delays and frustrations 

https://jira.hic.dundee.ac.uk/browse/RDMPSUP-156

### PR DESCRIPTION
**Pull request by tznind**
Fixes #683 

- Adds new class `ExtractionProgress` 
- Changes `ExtractionQueryBuilder` to detect when one of these is declared on a `SelectedDataSets` and adds in an extra line of `WHERE` SQL that brackets the dates of the records extracted
- Adds property `IsBatchResume` to execution time class `ExtractCommand` to allow estinations to opt into appending the destination (instead of overwritting/crashing).
- 
image

### TODO

- [x] Clone (a frozen) `ExtractionConfiguration` should clone and reset progress on any `ExtractionProgress` objects
- [x] Metadata report will be completely wrong and reflect only the last batch extracted
- [x] Release document will be completely wrong and reflect only the last batch extracted

```csharp
SetTableCell(t,rownum,0,"Cohort Size (Distinct)");
SetTableCell(t,rownum,1,Executer.Source.Request.ExtractableCohort.CountDistinct.ToString());
rownum++;

SetTableCell(t,rownum,0,"Cohorts Found In Dataset");
SetTableCell(t,rownum,1,Executer.Source.UniqueReleaseIdentifiersEncountered.Count.ToString());
rownum++;
```
_There doesn't seem like any good way to retain this functionality while enabling batching_

image

- [x] Unit tests
- [x] Fail/Resume means backing up the output file (CSV) 
- [x] Fail/Resume to db is sketchy and can't use transaction due to resizing columns and DDL operations which cause implicit commit on transactions

### CODE REVIEW

**Comment by tznind** [comment]
@RoyMudie currently the code in ExtractionProgressUI populate the text box and object in memory with the DQE dates but they do not call `SaveToDatabase`.  Do you want it to auto save when it opens that tab? Or do you want there to be a button 'populate dates from DQE' like Magalie was suggesting?

**Comment by RoyMudie** [comment]
Yeah, lets move that information over to a "DQE Data" type column that contains extra peices of information. I think it's important that it's visible to the user when the DQE was last run to give confidence the data is "correct". In fact, do we have a "DQEDataValid" type property that is true if the DQE has been run since the data was last updated?

**Comment by tznind** [comment]
image

**Comment by RoyMudie** [comment]
Three things I've noticed:
1. If you've already added extraction progress the error is wrong on the tooltip when trying to add it again
image
2. The "Use DQE Start/End Date" button either needs to say that, or have a tooltip
3. The progress textbox should be uneditable and make use of a "reset progress" button

**Review by RoyMudie — APPROVED** [review]

**Pull request merged**
