### PR TITLE
Updated FilterContainer_ID to return ID

### LINKED ISSUE #843: Tooltip for ExtractionFilter throws NotSupportedException exception
**Describe the bug**
Hover over a ExtractionFilter and you'll receive the following error:

`
System.NotSupportedException
  HResult=0x80131515
  Message=Specified method is not supported.
  Source=Rdmp.Core
  StackTrace:
   at Rdmp.Core.Curation.Data.ExtractionFilter.get_FilterContainer_ID() in C:\GitHub\HIC\RDMP\Rdmp.Core\Curation\Data\ExtractionFilter.cs:line 67
`

### PR DESCRIPTION
**Pull request by RoyMudie**
Closes #843 
image

### CODE REVIEW

**Comment by tznind** [comment]
This is not correct.  Those IDs are not the same.  

The API is correct.  'master filters' i.e. `ExtractionFilter` are Catalogue level filters so never belong inside a container.  Therefore it is illegal to ask for the ID of the container they belong to.

We should instead either override the `GetSummary` on `ExtractionFilter` to ignore that property or catch and skip `NotSupportedException` (which is the correct Exception type for when a method/property on an abstract base or interface is not supported by the API - not to be confused with `NotImplementedException` which is code for 'I've not written that yet').

**Comment by RoyMudie** [comment]
Gotcha. I "verified" it by checking it matched the ID column - but presumably this is a bug then?
image

**Comment by tznind** [comment]
> Gotcha. I "verified" it by checking it matched the ID column - but presumably this is a bug then?

`FilterContainer_ID` is the ID of a WHERE container that the filter is in.  Its a foreign key property effectively.  It says 'this filter belongs in that AND/OR container'.  The master filters cannot be part of a container so never have one.

**Comment by RoyMudie** [comment]
I see I was getting confused by `FilterContainer_ID` and the ID of the object.

The error is actually happening when it's appending the properties to the summary.

If we suppress all possible errors when adding the properties:
image

Then we end up with what I had before:
image

Maybe we need that conversation about IDs... Get back holidaying!

**Comment by RoyMudie** [comment]
Reminder for return to work: occured to me last night that we do a bunch of checks AFTER the `prop.GetValue(this)` call that if done before would avoid this issue all together.

**Review by tznind — APPROVED** [review]

**Pull request merged**
