### PR TITLE
Extraction workflow improvements

### LINKED ISSUE #983: Create Extraction Configuration workflow improvements
Creating a new extraction configuration
 - [x] RDMP should automatically ask for Extraction Name
 - [x] Auto-populate  Extraction Name with "PROJ_NUMBER YYYY/MM Extraction"
 - [x] RDMP should ask for datasets to be added to extraction (can be skipped)
 - [x] RDMP should then ask for saved cohorts to be added to the extraction (can be skipped)

### LINKED ISSUE #1039: Add option to create extraction from Cohort right click menu and ExtractableCohortUI
**Is your feature request related to a problem? Please describe.**
When viewing a corhot it should be striaght forward to move to the next step and extract it.

**Describe the solution you'd like**
- [x] Add option for "New Extraction Configuration using Cohort" to right click menu for a Cohort
- [x] Add the same option to the top bar of the ExtractableCohortUI

### PR DESCRIPTION
**Pull request by RoyMudie**
Fixes #1039
Fixes #983

### CODE REVIEW

**Comment by tznind** [comment]
I have fixed this to work better on command line and draw feasability of adding cohort/datasets direct from the command instead of doing a secondary lookup.


```
./rdmp cmd describecommand createnewextractionconfigurationforproject

Name: ExecuteCommandCreateNewExtractionConfigurationForProject

Description:
Creates a new ExtractionConfiguration under a given Project

USAGE:
./rdmp.exe cmd CreateNewExtractionConfigurationForProject <project> <name>

PARAMETERS:
project   Project             The Project under which to create the new ExtractionConfiguration
name      String              The name for the new ExtractionConfiguration


Command Completed

./rdmp cmd CreateNewExtractionConfigurationForProject Project:1 fffff
2022-04-20 11:57:27.4363 INFO Created New,ExtractionConfiguration .
Command Completed
```

**Comment by tznind** [comment]
@RoyMudie I have made some changes to this please check that you are happy with them and I will approve (as it is your PR I can't assing you a reviewer directly).

**Comment by RoyMudie** [comment]
Sorry @tznind #1039 was badly written, I've separated out the two tasks as we've missed adding the option to the ExtractableCohortUI
image

We should also make the default extraction name include the project number and I suggest we put the date in a format that makes them sort sensibly when done by name, i.e. "1234 2022-04-21 Extraction"

**Comment by tznind** [comment]
> we've missed adding the option to the ExtractableCohortUI

Ok I've added it in 4c77638

**Pull request merged**
