### PR TITLE
Drop System.Drawing from Rdmp.Core WIP

### LINKED ISSUE #1349: Find a replacement for Bitmap in ImageSharp
https://github.com/dotnet/designs/pull/234/files#diff-5a79205cd271d8ec2d3c5d74112f6874998e1e1aa7ee00900db727eef25561d8
 
- Port Rdmp.Core code that uses bitmaps to ImageSharp
- Translation layer for winforms client that converts those bitmaps into windows usable ones

### PR DESCRIPTION
**Pull request by tznind**
Fixes #1349

TODO:

- [x] Add `.ToBitmap()` to everywhere we convert ImageSharp Image to System.Drawing.Image (i.e. in winforms)
- [x] Port Grascale functionality
- [x] Port Overlay drawing functionality
- [x] Port 'create .ico file' functionality
- [ ] Port resize functionality
- [x] Get it to build
- [ ] Test it actually works

### CODE REVIEW

**Comment by tznind** [comment]
Since [c69a530](https://github.com/HicServices/RDMP/pull/1355/commits/c69a53044a3c72ae5c92cfb5c4e192e201b32ec8) I now get a big red X over top toolbar and the Painting thread is throwing 'Out of memory' Exception (process is using 196MB so its not really that).

```
   at System.Drawing.TextureBrush..ctor(Image image, WrapMode wrapMode)
   at System.Windows.Forms.ControlPaint.DrawBackgroundImage(Graphics g, Image backgroundImage, Color backColor, ImageLayout backgroundImageLayout, Rectangle bounds, Rectangle clipRect, Point scrollOffset, RightToLeft rightToLeft)
   at System.Windows.Forms.ToolStripProfessionalRenderer.RenderItemInternal(ToolStripItemRenderEventArgs e, Boolean useHotBorder)
   at System.Windows.Forms.ToolStripProfessionalRenderer.OnRenderButtonBackground(ToolStripItemRenderEventArgs e)
   at System.Windows.Forms.ToolStripRenderer.DrawButtonBackground(ToolStripItemRenderEventArgs e)
   at System.Windows.Forms.ToolStripButton.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandlePaint(PaintEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Comment by tznind** [comment]
Ok in [777b200](https://github.com/HicServices/RDMP/pull/1355/commits/777b20072ccaafda57f584afb5490eecdb4b35cf) I have reverted the changes in BackColorProvider.cs so that it works with `System.Drawing` again instead of ImageSharp.  That has fixed the above 'red x' issue. 

I think since that is in WinForms code we might as well leave that as it is.  I will do some more testing to make sure the fix doesn't just delay the error.

**Comment by tznind** [comment]
Looks like we will still have a dependency on System.Drawing.Common.dll via NPOI which is the Excel reading library

image

**Comment by jas88** [comment]
@tznind It's 6.0 where it was officially marked Windows-only. Upstream has ImageSharp as a dependency now - https://github.com/nissl-lab/npoi/blob/master/main/NPOI.csproj - but it looks like they haven't fired up a release since that change, so we need to wait for the next release to get this bit fixed.

**Review by jas88 — APPROVED** [review]

**Pull request merged**
