### PR TITLE
Cache control commands

### LINKED ISSUE #859: Improve cache status visabilty/options while editing a CIC
**Is your feature request related to a problem? Please describe.**
At the moment it's not very clear how to view that status of the Caching Database while editing a CIC.
The options for clearning the caching database is also hidden in the burger menu.
image

**Describe the solution you'd like**
Add icons, colour, text or additional submenu items to the Caching Database to make the status more obvious.

Add easy to access/find buttons options for clearning the cache, e.g. adding the option near ther "execute" button and/or to the right click menu for the caching database.
image
image

### PR DESCRIPTION
**Pull request by tznind**
Fixes #859 

image

Original Spec in Issue:
image

### CODE REVIEW

**Comment by RoyMudie** [comment]
Couple of things:

- Needs a tooltip for Clear Cache button (in fact, all those buttons need tooltips...)
- Don't think it makes sense to remove the Clear Cache from the burger menu. Maybe we should add a "Caching" submenu to that so it's more like:

Calculate Cumlative Totals
Caching
    Create New Query Cache Database
    Change Query Cache Database
    Clear Query Cache Database
Edit Description
Help

**Comment by tznind** [comment]
I've added tooltips and put the ClearCache command back into the burger bar menu.

The API currently doesn't support submenus in the burger bar so if that is something we want later on I think we could add that support but not worth blocking this PR based on it.

**Comment by RoyMudie** [comment]
Sorry, two minor issues:

- There's no tooltip for the button when the Clear Cache option is disalbed
- If there's no Caching Database we should probably hide the button (because it serves no purpose)

**Comment by tznind** [comment]
> Sorry, two minor issues:
> 
>     * There's no tooltip for the button when the Clear Cache option is disalbed

Disabled controls do not show tooltips.  The workarounds look janky as hell:

https://stackoverflow.com/questions/1732140/displaying-tooltip-over-a-disabled-control
 
>     * If there's no Caching Database we should probably hide the button (because it serves no purpose)

After talking decided not to do this

**Review by RoyMudie — APPROVED** [review]

**Pull request merged**
