### PR TITLE
Added ability to switch between instances

### LINKED ISSUE #694: Have all RDMP instances in one app [Magalie]
RDMP can have multiple sessions we work with. For instance with DATA team, there is a minimum of RDMP HIC data and RDMP Share. In order to run one or the other, one is set up as session by default in RDMP app, the other is opened using a bat file (manually created). Can RDMP deal with multiple instance without having to close one app to open another?

In attachment below, an example of what it could look like visually for users based on how Teams deal with multiple instances. This visual is quite standard and understandable to any type of user 

image

https://jira.hic.dundee.ac.uk/browse/RDMPSUP-137

### LINKED ISSUE #864: Add instance name when using Database yaml files
image

### PR DESCRIPTION
**Pull request by tznind**
Fixes #694
Fixes #864

image

### CODE REVIEW

**Comment by tznind** [comment]
TODO:

- Add name and description to yaml
- Find valid yaml files in a smarter way (currently just the RDMP binaries location)
- Make this feature work corectly when yaml files are specifiied that are not in the RDMP bin dir

**Comment by tznind** [comment]
Tooltips seem to pop under now but perhaps windows 11 will fix that ;) want me to remove them

image

**Comment by RoyMudie** [comment]
I think that's a race condition between the sub menu item appearing and the tooltip as the tooltip appears on top of a second before disapearing behind the menu when the sub menu pops up.

You can "fix" it by hovering over the sub menu, then back to the "Launch Another Instance" menu item:
image

It also works if you click on the option "Launch Another Instance" option before the delay.

Maybe try changing the menu submenu auto-popup delay to be quicker than the tooltip delay?

**Comment by tznind** [comment]
> Maybe try changing the menu submenu auto-popup delay to be quicker than the tooltip delay?

I don't think that's an option on `ToolStripMenuItem`.  Happy to leave it unless you have a code fix to submit?

**Comment by tznind** [comment]
image

**Review by RoyMudie — APPROVED** [review]

**Pull request merged**
